name: URL Shortener CI

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    backend-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23'
            
            - name: Install dependencies
              run: go mod tidy

            - name: Run build
              run: go build ./...

    backend-test:
        runs-on: ubuntu-latest
        needs: backend-build
        defaults:
            run:
                working-directory: backend

        services:
            postgres:
                image: postgres:15
                ports:
                  - 5432:5432
                env:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_DB: url_shortener_test
                options: >-
                  --health-cmd="pg_isready -U postgres -d url_shortener_test"
                  --health-interval=10s
                  --health-timeout=5s
                  --health-retries=5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23'

            - name: Install dependencies
              run: go mod tidy
              
            - name: Run tests
              env: 
                DATABASE_URL: postgres://postgres:postgres@localhost:5432/url_shortener_test?sslmode=disable
              run: go test -v ./...